# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/djidonoujustin11@gmail.com/Amazon_Report-Pipeline")

# COMMAND ----------

# !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

display(spark.sql("SELECT * FROM amazon_sales_catalog.gold_schema.sample_aggregation_amazon_report_pipeline"))

# COMMAND ----------

df = spark.sql(
    """
    SELECT *
    FROM amazon_sales_catalog.gold_schema.dwh_dim_location
    """
)
display(df)

# COMMAND ----------

# MAGIC %md
# MAGIC ###Quelles sont les 5 Catégories de Produits les Plus Vendues ?

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT
# MAGIC     P.Category,
# MAGIC     SUM(F.Qty) AS Total_Qty
# MAGIC FROM
# MAGIC     amazon_sales_catalog.gold_schema.dwh_fact_sales as F
# MAGIC INNER JOIN
# MAGIC     amazon_sales_catalog.gold_schema.dwh_dim_product as P ON F.ProductKey = P.product_key 
# MAGIC WHERE 
# MAGIC     P.__END_AT IS NULL AND P.Category IS NOT NULL
# MAGIC GROUP BY
# MAGIC     P.Category
# MAGIC ORDER BY
# MAGIC     Total_Qty DESC
# MAGIC LIMIT 5;

# COMMAND ----------

# MAGIC %md
# MAGIC ###Quelle est la contribution au Chiffre d'Affaires de chaque État ?
# MAGIC
# MAGIC

# COMMAND ----------

# MAGIC
# MAGIC
# MAGIC %sql
# MAGIC SELECT
# MAGIC     L.ShipState AS State, 
# MAGIC     SUM(F.Amount) AS Revenue
# MAGIC FROM
# MAGIC     amazon_sales_catalog.gold_schema.dwh_fact_sales AS F
# MAGIC INNER JOIN
# MAGIC     amazon_sales_catalog.gold_schema.dwh_dim_location AS L 
# MAGIC     ON F.LocationKey = L.location_key 
# MAGIC WHERE 
# MAGIC     L.__END_AT IS NULL 
# MAGIC GROUP BY
# MAGIC     L.ShipState
# MAGIC ORDER BY
# MAGIC     Revenue DESC
# MAGIC LIMIT 10
# MAGIC
# MAGIC
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ### Quelle est la tendance des ventes mensuelles (croissance) en termes de chiffre d'affaires
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT
# MAGIC     T.Year,                       
# MAGIC     T.Month,                      
# MAGIC     SUM(F.Amount) AS Monthly_Revenue 
# MAGIC FROM
# MAGIC     amazon_sales_catalog.gold_schema.dwh_fact_sales AS F
# MAGIC INNER JOIN
# MAGIC     amazon_sales_catalog.gold_schema.dwh_dim_time AS T
# MAGIC     ON F.TimeKey = T.TimeKey 
# MAGIC GROUP BY
# MAGIC     T.Year,
# MAGIC     T.Month
# MAGIC ORDER BY
# MAGIC     T.Year ASC,
# MAGIC     T.Month ASC; 

# COMMAND ----------

# MAGIC %md
# MAGIC ###Quelle est la distribution des commandes par Statut final ou actuel ?

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT
# MAGIC     O.orderStatus,
# MAGIC     COUNT(F.SalesKey) AS TotalOrders
# MAGIC FROM
# MAGIC     amazon_sales_catalog.gold_schema.dwh_fact_sales AS F
# MAGIC INNER JOIN
# MAGIC     amazon_sales_catalog.gold_schema.dwh_dim_orderStatus AS O 
# MAGIC     ON F.OrderStatusKey = O.status_key 
# MAGIC WHERE 
# MAGIC     O.__END_AT IS NULL  
# MAGIC GROUP BY
# MAGIC     O.orderStatus
# MAGIC ORDER BY
# MAGIC     TotalOrders DESC
# MAGIC LIMIT 10